from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('subjects/', views.subjects, name='subjects'),
    path('admission/', views.admission, name='admission'),
    path('fees_payment/', views.feespayment, name='feespayment'),
    path('apply_online/', views.onlineApp, name='onlineApp'),
    path('approve_application/', views.approveApplication, name='application_confirmation'),
    path('approve_application/<str:id>', views.student_application_approval, name='student_application_approval'),
    path('decline_application/<str:id>', views.student_application_decline, name='student_application_decline'),
    path('delete_student/<str:pk>', views.deleteStudent, name='deleteStudent'),
    path('student_information/<str:pk>', views.studentInfo, name='studentInfo'),
    path('all_teachers/', views.all_teachers, name='all_teachers'),
    path('teacher_info/<str:pk>', views.teacherInfo, name='teacher_info'),
    path('class_info/<str:pk>', views.classInfo, name='classInfo'),
    path('class_infomation/<str:pk>', views.teacherClass, name='teacherClass'),
    path('report_card/<str:pk>', views.reportCard, name='reportCard'),
    path('student_report_card/<str:pk>', views.studentReportCard, name='studentReportCard'),
    path('subject_info/<str:pk>', views.subjectInfo, name='subjectInfo'),
    path('subject_students/<str:pk>', views.subjectStudents, name='subjectStudents'),
    path('update_student_results/<str:pk>', views.updateResults, name='updateResults'),
    path('add_subject/', views.addSubject, name='addSubject'),
    path('view_subjects/', views.viewSubject, name='viewSubject'),
    path('update_subject/<str:pk>', views.updateSubject, name='updateSubject'),
    path('delete_subject/<str:pk>', views.deleteSubject, name='deleteSubject'),
    path('account_settings/', views.studentAccountSettings, name='studentAccountSettings'),
    path('account_settings_principal/', views.principalAccountSettings, name='principalAccountSettings'),
    path('add_teacher/', views.addTeacher, name='addTeacher'),
    path('update_teacher/<str:pk>', views.updateTeacher, name='updateTeacher'),
    path('remove_student_from_class/<str:pk>', views.removeStudentFromClass, name='removeStudentFromClass'),
    path('remove_student_from_subject/<str:pk>', views.removeStudentFromSubject, name='removeStudentFromSubject'),
    path('add_class/', views.addClass, name='addClass'),
    path('update_class/<str:pk>', views.updateClass, name='updateClass'),
    path('delete_class/<str:pk>', views.deleteClass, name='deleteClass'),
    path('view_classes/', views.viewClasses, name='viewClasses'),
    path('contact_us/', views.contact, name='contact'),
    path('my_subjects/', views.mySubjects, name='mySubjects'),
    path('my_results/', views.myResults, name='myResults'),
    path('my_results_pdf/', views.studentReportPdf, name='studentReportPdf'),
    path('all_students_pdf/', views.allStudentsPdf, name='all_students_pdf'),
    path('delete_teacher/<str:pk>', views.deleteTeacher, name='deleteTeacher'),
    path('login/', views.loginUser, name='login'),
    path('student_login/', views.loginStudent, name='loginStudent'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.userRegister, name='userRegister'),
    path('student_register/', views.studentRegister, name='studentRegister'),
    path('update_student/<str:pk>', views.updateStudent, name='updateStudent'),
    path('admin_dashboard/', views.adminDashboard, name='adminDashboard'),
    path('online_applications/', views.onlineApplications, name='onlineApplications'),
    path('applicant_info<str:pk>/', views.applicantInfo, name='applicantInfo'),
    path('application_confirmation/<str:pk>/', views.approveApplication, name='approveApplication'),
    path('application_rejection/<str:pk>/', views.rejectApplication, name='rejectApplication'),
    path('student_registration/', views.studentRegistration, name='studentReg'),
    path('all_students/', views.viewStudents, name='viewStudents'),
    path('receptionist_dashboard/', views.receptionistDashboard, name='receptionistDashboard'),
    path('teacher_dashboard/', views.teacherDashboard, name='teacherDashboard'),
    path('student_dashboard/', views.studentDashboard, name='studentDashboard'),
    path('staff_gallery/', views.staffGallery, name='staffGallery'),
    path('student_gallery/', views.studentGallery, name='studentGallery'),
    path('events_gallery/', views.eventsGallery, name='eventsGallery'),

    path('change_password/',
     auth_views.PasswordChangeView.as_view(template_name='dashboard/principalDashboard/principalChangePassword.html'),
      name='principalChangePassword'),

    path('change_password_student/',
     auth_views.PasswordChangeView.as_view(template_name='dashboard/StudentDashboard/studentChangePassword.html'),
      name='studentChangePassword'),
    
    path('password_change_done/',
     auth_views.PasswordChangeDoneView.as_view(template_name='dashboard/principalDashboard/principalChangePasswordDone.html'),
      name='password_change_done'),

    path('password_change_done_student/',
     auth_views.PasswordChangeDoneView.as_view(template_name='dashboard/studentDashboard/studentChangePasswordDone.html'),
      name='password_change_done'),  

    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name='main/password_reset.html'),
     name='reset_password'),
    path('reset_password_sent/',
     auth_views.PasswordResetDoneView.as_view(template_name='main/password_reset_sent.html'),
      name='password_reset_done'),
    path('reset/uidb64/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name='main/passwordResetForm.html'),
      name='password_reset_confirm'),
    path('reset_password_complete/',
     auth_views.PasswordResetCompleteView.as_view(template_name='main/password_reset_done.html'),
      name='password_reset_complete'),
]