# Generated by Django 4.2.1 on 2023-07-18 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_studentinsubject_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentinclass',
            unique_together={('student', 'student_class')},
        ),
    ]
