# Generated by Django 4.2.1 on 2023-07-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_studentinsubject_grade_studentinsubject_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinsubject',
            name='mark',
            field=models.PositiveIntegerField(blank=True, max_length=100, null=True),
        ),
    ]
