# Generated by Django 4.2.1 on 2023-07-27 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_studentinsubject_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.classlevel'),
        ),
        migrations.AlterField(
            model_name='studentinsubject',
            name='mark',
            field=models.PositiveIntegerField(blank=True, max_length=3, null=True),
        ),
    ]
