# Generated by Django 4.2.1 on 2023-07-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_student_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='applicant_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
