# Generated by Django 4.2.1 on 2023-07-31 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_applicant_applicant_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.classlevel'),
        ),
    ]
